In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.metrics import accuracy_score

In [43]:
sample_file_path="./samples.csv"
df_site=pd.read_csv(sample_file_path)

In [44]:
df_site

id                                                url  \
0      1                                    http://esto.es/   
1      2                        http://gg.gg/child_cartoons   
2      3                                  http://gmail.com/   
3      4                              http://mirabelle.uno/   
4      5  https://api.whatsapp.com/send/?phone=967716800...   
..   ...                                                ...   
283  284                                  http://4.FO/JiMaT   
284  285                                 http://cliick.fun/   
285  286                                http://hotwife.uno/   
286  287                               http://porngirl.uno/   
287  288                                 http://amoera.cam/   

                                          landing_page  a_count  img_count  \
0                           http://esto.es/defaultsite        0          0   
1                                        http://gg.gg/       13          6   
2    https://accounts.google.com/v3/signin/identifi...        6          1   
3    https://www.benaughty.com/aff.php?btUrl=aHR0cH...        4        145   
4    https://api.whatsapp.com/send/?phone=967716800...       97          2   
..                                                 ...      ...        ...   
283                https://dhaaeh.datinglocator24.com/        0          0   
284  https://odzrea.speciaidates.com/c/1e3a4e532f1c...        5         35   
285  https://dirtyflirt6.com/?a=1192171&cr=48591&li...       10          0   
286  https://moartraffic.engine.adglare.net/?290938...        0          0   
287  https://racywomenm0.com/?a=1829848&cr=48591&li...       10          0   

     iframe_count  button_count  div_count  class_count  words_count  ...  \
0               0             0          1            0            0  ...   
1               2             0         16            4          289  ...   
2               1             1         26           40          753  ...   
3               0             0        296          101         1127  ...   
4               0             4         40           67         1156  ...   
..            ...           ...        ...          ...          ...  ...   
283             0             0          0            0            7  ...   
284             0            13        149          124          935  ...   
285             0             0         50           33          356  ...   
286             0             0          0            0            1  ...   
287             0             0         40           28          356  ...   

     link_count    a_http   a_https  link_http  link_https    a_diff  \
0             0  0.000000  0.000000        0.0         0.0  0.000000   
1             5  0.384615  0.000000        1.0         0.0  0.153846   
2             1  0.000000  0.333333        0.0         0.0  0.333333   
3             3  0.000000  1.000000        0.0         1.0  0.000000   
4            13  0.000000  0.010309        0.0         0.0  0.371134   
..          ...       ...       ...        ...         ...       ...   
283           0  0.000000  0.000000        0.0         0.0  0.000000   
284           5  0.000000  0.000000        0.0         1.0  0.000000   
285           0  0.000000  0.300000        0.0         0.0  0.000000   
286           0  0.000000  0.000000        0.0         0.0  0.000000   
287           1  0.000000  0.300000        0.0         0.0  0.000000   

     link_diff  a_hashtag  link_hashtag  tag  
0          0.0   0.000000             0    1  
1          0.0   0.307692             0    1  
2          0.0   0.000000             0    1  
3          0.0   0.000000             0    1  
4          1.0   0.000000             0    1  
..         ...        ...           ...  ...  
283        0.0   0.000000             0    0  
284        0.0   0.800000             0    0  
285        0.0   0.700000             0    0  
286        0.0   0.000000             0    0  
287  

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X, y = df_site.iloc[:, 3:-2].values, df_site.iloc[:,-1].values

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [48]:
X_train, X_test, y_train, y_test

(array([[17.       ,  1.       ,  0.       , ...,  0.529412 ,  0.5      ,
          0.0588235],
        [20.       ,  3.       ,  2.       , ...,  0.2      ,  0.923077 ,
          0.       ],
        [30.       , 12.       ,  2.       , ...,  0.166667 ,  0.886364 ,
          0.       ],
        ...,
        [ 1.       , 10.       ,  1.       , ...,  0.       ,  1.       ,
          0.       ],
        [17.       ,  1.       ,  0.       , ...,  0.529412 ,  0.5      ,
          0.0588235],
        [ 0.       ,  1.       ,  1.       , ...,  0.       ,  0.892857 ,
          0.       ]]),
 array([[10.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
          0.7      ],
        [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
          0.       ],
        [17.       ,  1.       ,  0.       , ...,  0.529412 ,  0.5      ,
          0.0588235],
        ...,
        [40.       , 41.       ,  2.       , ...,  0.125    ,  0.886364 ,
          0.       ],
        [ 4.

In [49]:
from sklearn.preprocessing import MinMaxScaler

In [50]:
mms=MinMaxScaler()

In [51]:
X_train_norm=mms.fit_transform(X_train) # 最大-最小特征缩放

In [52]:
X_test_norm=mms.fit_transform(X_test)

In [53]:
X_test_norm

array([[0.0462963 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.7       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0787037 , 0.0045045 , 0.        , ..., 1.        , 0.5       ,
        0.0588235 ],
       ...,
       [0.18518519, 0.18468468, 1.        , ..., 0.23611101, 0.886364  ,
        0.        ],
       [0.01851852, 0.03153153, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0462963 , 0.04054054, 0.        , ..., 0.75555522, 0.142857  ,
        0.        ]])

In [54]:
from sklearn.preprocessing import StandardScaler

In [55]:
stdsc=StandardScaler()
X_train_std=stdsc.fit_transform(X_train)
X_test_std=stdsc.fit_transform(X_test)

In [56]:
from sklearn.linear_model import LogisticRegression

In [63]:
lr=LogisticRegression(C=1.0,random_state=1,solver='lbfgs',multi_class='multinomial')
lr.fit(X_train_std, y_train)
y_pred=lr.predict(X_test_std)
print('accuracy_score: %.3f' % accuracy_score(y_test, y_pred))

accuracy_score: 0.989


In [58]:
from sklearn.svm import SVC

In [59]:
svm = SVC(kernel='rbf', random_state=1, gamma='scale', C=1.0)
svm.fit(X_train_std, y_train)
y_pred = svm.predict(X_test_std)
print('accuracy_score: %.3f' % accuracy_score(y_test, y_pred))

accuracy_score: 0.989


In [60]:
from sklearn.tree import DecisionTreeClassifier

In [66]:
tree_model=DecisionTreeClassifier(criterion='gini',max_depth=5,random_state=100)
tree_model.fit(X_train_std,y_train)
y_pred = tree_model.predict(X_test_std)
print('accuracy_score: %.3f' % accuracy_score(y_test, y_pred))

accuracy_score: 0.989
