In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.metrics import accuracy_score


In [2]:
sample_file_path="./samples.csv"
df_site=pd.read_csv(sample_file_path)

In [3]:
df_site

a_count  img_count  iframe_count  button_count  div_count  class_count  \
0          0         13             1             2         23           24   
1          0          0             1             0          1            0   
2         12          5             2             0         15            4   
3          6          1             1             1         26           40   
4        180         47             1            32        333           88   
..       ...        ...           ...           ...        ...          ...   
451       19         14             0             2        109          142   
452       10          0             0             0         40           28   
453       15          3             0             0         49           44   
454        5         35             0            13        149          124   
455       15          3             0             0         49           44   

     words_count  tag  
0            102    1  
1              0    1  
2            289    1  
3            753    1  
4           5187    1  
..           ...  ...  
451          646    0  
452          356    0  
453          249    0  
454          935    0  
455          249    0  

[456 rows x 8 columns]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X, y = df_site.iloc[:, :-2].values, df_site.iloc[:,-1].values

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [7]:
X_train, X_test, y_train, y_test

(array([[ 22,  31,   1,  25, 618, 261],
        [ 13,  11,   1,   7,  88,  70],
        [ 10,   1,   1,   7, 151, 120],
        ...,
        [ 10,   4,   1,   2, 119, 127],
        [ 96,  13,   1,   2, 152, 166],
        [ 12,   1,   1,   7, 151, 120]], dtype=int64),
 array([[  0,   1,   1,   7,  66,  37],
        [ 13,  11,   1,   7,  88,  70],
        [ 10,  12,   1,   1, 118,  97],
        [  8,   6,   0,   0,  32,  21],
        [ 18,   2,   0,   1,  26,  51],
        [  7,   1,   0,   0,  51,  35],
        [ 25,  14,   1,  27, 645, 283],
        [ 15,   3,   0,   0,  49,  44],
        [ 40,  39,   1,  22, 702, 267],
        [ 17,   1,   0,   1,  88, 100],
        [ 13,   2,   5,   1,  64,  72],
        [ 37,  25,   0,   6, 145, 146],
        [153,   0,   8,   0, 718, 173],
        [ 10,   1,   1,   7, 151, 120],
        [ 10,   0,   0,   0,  40,  28],
        [  5,  35,   0,  13, 149, 124],
        [ 44,   3,   4,   6, 125, 110],
        [ 10,   0,   0,   0,  40,  28],
        [354

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
mms=MinMaxScaler()

In [10]:
X_train_norm=mms.fit_transform(X_train) # 最大-最小特征缩放

In [11]:
X_test_norm=mms.fit_transform(X_test)

In [12]:
X_test_norm

array([[0.        , 0.0045045 , 0.08333333, 0.25925926, 0.06653226,
        0.06666667],
       [0.03672316, 0.04954955, 0.08333333, 0.25925926, 0.08870968,
        0.12612613],
       [0.02824859, 0.05405405, 0.08333333, 0.03703704, 0.11895161,
        0.17477477],
       [0.02259887, 0.02702703, 0.        , 0.        , 0.03225806,
        0.03783784],
       [0.05084746, 0.00900901, 0.        , 0.03703704, 0.02620968,
        0.09189189],
       [0.01977401, 0.0045045 , 0.        , 0.        , 0.05141129,
        0.06306306],
       [0.07062147, 0.06306306, 0.08333333, 1.        , 0.65020161,
        0.50990991],
       [0.04237288, 0.01351351, 0.        , 0.        , 0.04939516,
        0.07927928],
       [0.11299435, 0.17567568, 0.08333333, 0.81481481, 0.70766129,
        0.48108108],
       [0.0480226 , 0.0045045 , 0.        , 0.03703704, 0.08870968,
        0.18018018],
       [0.03672316, 0.00900901, 0.41666667, 0.03703704, 0.06451613,
        0.12972973],
       [0.10451977, 0

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
stdsc=StandardScaler()
X_train_std=stdsc.fit_transform(X_train)
X_test_std=stdsc.fit_transform(X_test)

In [15]:
from sklearn.linear_model import LogisticRegression

In [106]:
lr=LogisticRegression(C=1.0,random_state=1,solver='lbfgs',multi_class='multinomial')
lr.fit(X_train_std, y_train)
y_pred=lr.predict(X_test_std)
print('accuracy_score: %.3f' % accuracy_score(y_test, y_pred))


accuracy_score: 0.803


In [66]:
from sklearn.svm import SVC

In [81]:
svm = SVC(kernel='rbf',random_state=1,gamma=5,C=1.0)
svm.fit(X_train_std, y_train)
y_pred = svm.predict(X_test_std)
print('accuracy_score: %.3f' % accuracy_score(y_test, y_pred))

accuracy_score: 0.847


In [83]:
from sklearn.tree import DecisionTreeClassifier

In [109]:
tree_model=DecisionTreeClassifier(criterion='gini',max_depth=6,random_state=10)
tree_model.fit(X_train_std,y_train)
y_pred = tree_model.predict(X_test_std)
print('accuracy_score: %.3f' % accuracy_score(y_test, y_pred))

accuracy_score: 0.657
